version: '3.8'
# 도커에 레디스 추가용
services:
  redis:
    image: redis:7.2
    container_name: redis-single
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis-data:
